### ISSUE TITLE
Hide Menu Bar Item

### ISSUE THREAD

**Issue by khesed** [ris58h/Touch-Tab#17]
Could you make an option to hide the menu bar item? This could be implemented like [`MiddleClick-Ventura`](https://github.com/artginzburg/MiddleClick-Ventura/blob/879bdf08bfd2468f659617916417ad61767e52b8/README.md?plain=1#L76)

> While holding `⌘`, drag the icon away from the status bar until you see a ✖️ (cross icon)
> Let it go
> To recover the item, just open MiddleClick when it's already running

**Comment by ris58h** [comment]
Available in `1.5.0` release.
