### ISSUE TITLE
Only cycles through apps when swiping left, swiping right only cycles two apps

### ISSUE THREAD

**Issue by mikecm1** [ris58h/Touch-Tab#18]
This might be a system issue, but when I swipe left the app works as expected (awesome), but when I swipe right, it goes back and forth between the top-most app and the one I previously used.

Cmd-shift-tab cycles through all apps, cmd-tab only two.

**Comment by ris58h** [comment]
This is how macOS App Switcher works. Touch-Tab just emulates key presses (Cmd+Tab or Cmd+Shift+Tab) on 3-finger swipe (right or left).

You can use long 3-finger swipe to right (or left) to select exact app.
