### ISSUE TITLE
Feature request: switch tabs

### ISSUE THREAD

**Issue by plakhin** [ris58h/Touch-Tab#2]
It would be very nice to have an option to switch application tabs instead of applications with 3 fingers swipe.

**Comment by ris58h** [comment]
I would like to keep Touch-Tab as simple as possible. “Do one thing, and do it well.” as in Unix philosophy.
You could try other software that could meet your requirements:
- [BetterTouchTool](https://folivora.ai/)
- [Multitouch](https://multitouch.app/)
- [Jitouch](https://github.com/JitouchApp/Jitouch)
