### ISSUE TITLE
AltTab mac app support

### ISSUE THREAD

**Issue by xAK7x** [ris58h/Touch-Tab#23]
I want to preface this by saying the functionality of touch-tab works well on its own, however with the AltTab mac app installed it starts to lose its ability to switch between apps, it would be great if it is possible to use both apps simultaneously for ultimate app switching productivity

**Comment by ris58h** [comment]
Could you elaborate more? I have both AltTab and Touch-Tab installed and they both work as expected.

**Comment by xAK7x** [comment]
when I swipe right it brings up the AltTab app switcher menu instead of changing applications, and it is a struggle swiping left to applications in the app switcher menu

**Comment by ris58h** [comment]
What happens when you press and hold Cmd+Tab? Does it show built-in macOS AppSwitcher or AltTab UI?

**Comment by xAK7x** [comment]
It brings up the AltTab UI with the macOS theme applied

**Comment by ris58h** [comment]
Touch-Tab emulates `Cmd+Tab` that's how it works.

There is an [issue](https://github.com/lwouis/alt-tab-macos/issues/730) in AltTab project to support swipe gestures.

**Comment by ris58h** [comment]
Possible workaround would be to change AltTab shortcut to something else. For example, `Option+Tab` (it's the default value BTW).

**Comment by ris58h** [comment]
@xAK7x JFYI the latest version of AltTab should support trackpad gestures. See https://github.com/lwouis/alt-tab-macos/issues/730
