### ISSUE TITLE
Needs to be updated

### ISSUE THREAD

**Issue by JtheLyn** [ris58h/Touch-Tab#25]
This software needs to be updated. Contact the developer for more information.
<img width="256" alt="Screenshot 2024-11-12 at 9 48 28 AM" src="https://github.com/user-attachments/assets/be9a63d5-8c71-4de0-9e4a-39df48ba5011">

**Comment by ris58h** [comment]
Please read [Installation](https://github.com/ris58h/Touch-Tab?tab=readme-ov-file#installation) or [Troubleshooting](https://github.com/ris58h/Touch-Tab?tab=readme-ov-file#troubleshooting) sections in README.
