### ISSUE TITLE
Integrate with popular open-source app AltTab

### ISSUE THREAD

**Issue by shayantist** [ris58h/Touch-Tab#6]
First off, thanks so much for making this tool! I recently just switched over from Windows to MacOS and swiping with three fingers to switch between windows became nearly second nature for me. This tool bringing some of that functionality over to Mac is truly a godsend!! 

One thing that I've been missing though is the ability to switch between windows instead of apps (similar to how another popular open source mac app [AltTab](https://github.com/lwouis/alt-tab-macos/) does it). I often have multiple windows of the same app open (especially web browsers and Finder windows), so the ability to switch between them quickly would be really helpful. A [similar issue](https://github.com/lwouis/alt-tab-macos/issues/756) was brought up there to implement this, but it looks like its incredible developer, lwouis sadly doesn't have the bandwidth to add it. 

This is probably a stretch, but would it be possible to integrate the three-finger swipe functionality of this app with the window switching of AltTab? Thanks so much for all your time developing and maintaining this, and for being open to suggestions!

**Comment by ris58h** [comment]
Thank you.

I'm already aware of the AltTab's issue (there is another one about scrolling https://github.com/lwouis/alt-tab-macos/issues/730 BTW) but I would like to keep Touch-Tab as simple as possible and I believe that it should be implemented on AltTab's side.

It's sad that AltTab is in such unclear state right now but it seems like the project is still active and @lwouis still maintains it.

**Comment by ris58h** [comment]
@shayantist JFYI the latest version of AltTab should support the trackpad gestures. See https://github.com/lwouis/alt-tab-macos/issues/730
